version: '3.7'
services:

  nginx:
    container_name: gallery_nginx
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-enabled

  php:
    build: docker/php/
    container_name: gallery_php
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/var/www/html

  postgres:
    container_name: gallery_postgres
    image: postgres
    ports:
      - 5433:5434
    environment:
      - POSTGRES_DB=nft
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    container_name: gallery_redis
    image: "redis"
    ports:
      - 6381:6379

  pgadmin:
    image: dpage/pgadmin4
    container_name: gallery_pgadmin
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

volumes:
  dbdata:
    driver: local
